### ISSUE TITLE
Superposición 

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/rollingGourmetLucasY#1]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar una superposición. 

## Resultado actual

• Se encuentra una superposición con el footer. 

## Captura

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/963486a0-7575-4042-bef4-01ae22591b03)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**Solucionado**
