### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/rollingGourmetLucasY#2]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que los botones redirijan a su dicho lugar o a un 404 (footer).

## Resultado actual

• Los botones no cumplen ninguna función.

## Captura

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/dab5a32a-3a68-4cee-b6fa-c9429ba215da)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**Solucionado**
