### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/rollingGourmetLucasY#3]
## Proceso

1. Ingrese a la pagina.
2. Llene el formulario de contacto.

## Resultado esperado

• Que no permitan numeros, signos ni espacios en blancos en el nombre del usuario.
• Encontrar un limite de caracteres a colocar en el mensaje.

## Resultado actual

• Se permiten colocar numeros, signos y espacios en blancos.
• No hay un limite de caracteres a colocar.
• Al enviar el mensajes se genera un error en consola.

## Captura

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/6a005bd6-d385-4420-8a4b-5e067d936e6e)
![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/cb46621e-ba95-47d7-a5ad-d055406eda76)

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/6f395113-0eec-474f-ae7e-96fc9d3172c5)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**solucionado**
