### ISSUE TITLE
Reservas

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/rollingGourmetLucasY#4]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise hacer una reserva.

## Resultado esperado

• No poder reservar fechas pasadas.

## Resultado actual

• Se pueden reservar fechas pasadas.

## Captura

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/1f9833b5-7719-4d70-8759-9b1274e9e8fd)
![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/04f08006-67b8-406f-ba26-15b10b8edbb0)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**Solucionado**
