### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Nidev-lab** [Lucasybanez/rollingGourmetLucasY#5]
## Proceso

1. Ingrese a la pagina.
2. Hice responsive en mobile.

## Resultado esperado

• Que el botón hamburguesa se encuentra separado del borde.

## Resultado actual

• El boton se encuentra pegado al borde.

## Captura

![image](https://github.com/Lucasybanez/rollingGourmetLucasY/assets/53904695/d969bc2b-0a7e-4e89-9785-0d4c5dcaf137)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucasybanez** [comment]
**Solucionado**
